USE BootcampTraining;
GO
CREATE OR ALTER PROCEDURE Sorted_Procedure_FEDAK
	@BrandName VARCHAR(40),
	@Name VARCHAR(40),
	@MaxSpeed INT
AS
BEGIN
BEGIN TRANSACTION
BEGIN TRY
	INSERT INTO CarBrand(Name)
	VALUES(@BrandName)

	INSERT INTO CarModel(BrandId,Name,MaxSpeed)
	VALUES (SCOPE_IDENTITY(),@Name,@MaxSpeed)

	COMMIT TRANSACTION
END TRY
BEGIN CATCH
	IF @@TRANCOUNT>0
		BEGIN
			ROLLBACK TRANSACTION
		END
	DECLARE @ErrMsg NVARCHAR(4000),@ErrSeverity INT
	SELECT @ErrMsg= ERROR_MESSAGE(),@ErrSeverity=ERROR_SEVERITY()

	RAISERROR(@ErrMsg,@ErrSeverity,1)
END CATCH
END
